#!/bin/bash

ulimit -n 9999

go build
if [ $? -ne 0 ]; then
    exit 1
fi

#./NASP --reference /scratch/jsahl/genomes/Ecoli/255_genomes/BSR/nasp_J_2/reference/reference.fasta /scratch/jsahl/genomes/Ecoli/255_genomes/BSR/nasp_J_2/external/*.frankenfasta
#./gonasp --duplicates benchmarks/Ecoli/duplicates.txt --reference benchmarks/Ecoli/reference.fasta benchmarks/Ecoli/external/*.frankenfasta
#./gonasp --reference benchmarks/Ecoli/reference.fasta benchmarks/Ecoli/external/*.frankenfasta
./gonasp --reference-dups benchmarks/Ecoli/duplicates.txt --reference-fasta benchmarks/Ecoli/reference.fasta benchmarks/Ecoli/external/*.frankenfasta


#go tool pprof -svg nasp cpu.pprof > cpu.svg
go tool pprof -svg gonasp mem.pprof > inuse_mem.svg
go tool pprof -alloc_space -svg gonasp mem.pprof > alloc_mem.svg
#go tool pprof -total_delay -contentions -mean_delay -lines -svg nasp block.pprof > block.svg
#go tool pprof -svg nasp block.pprof > block.svg

#go tool pprof -base mem.old.pprof -svg nasp mem.pprof > inuse_mem.delta.svg
#go tool pprof -base mem.old.pprof -alloc_space -svg nasp mem.pprof > alloc_mem.delta.svg

#open cpu.svg mem.svg block.svg
#open inuse_mem.svg alloc_mem.svg block.svg
#open inuse_mem.svg alloc_mem.svg
